### ISSUE TITLE
Fix spec failures

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/rfcxml#1]
These failures are due to some broken functionality inside Lutaml::Model.

Failing specs:
```
Rfcxml::V3::Rfc
  round-trips rfc8650.xml with equivalent-xml (FAILED - 1)
  round-trips rfc8650.xml with xml-c14 (FAILED - 2)
  round-trips rfc8651.xml with equivalent-xml (FAILED - 3)
  round-trips rfc8651.xml with xml-c14 (FAILED - 4)

Failures:

  1) Rfcxml::V3::Rfc round-trips rfc8650.xml with equivalent-xml
     Failure/Error:
       output = parsed.to_xml(
         pretty: true,
         declaration: true,
         encoding: "utf-8",
       )
     
     NoMethodError:
       undefined method `type' for nil
     # ./spec/v3/rfc_spec.rb:17:in `block (3 levels) in <top (required)>'

  2) Rfcxml::V3::Rfc round-trips rfc8650.xml with xml-c14
     Failure/Error:
       output = parsed.to_xml(
         pretty: true,
         declaration: true,
         encoding: "utf-8",
       )
     
     NoMethodError:
       undefined method `type' for nil
     # ./spec/v3/rfc_spec.rb:29:in `block (3 levels) in <top (required)>'

  3) Rfcxml::V3::Rfc round-trips rfc8651.xml with equivalent-xml
     Failure/Error:
       output = parsed.to_xml(
         pretty: true,
         declaration: true,
         encoding: "utf-8",
       )
     
     NoMethodError:
       undefined method `type' for nil
     # ./spec/v3/rfc_spec.rb:17:in `block (3 levels) in <top (required)>'

  4) Rfcxml::V3::Rfc round-trips rfc8651.xml with xml-c14
     Failure/Error:
       output = parsed.to_xml(
         pretty: true,
         declaration: true,
         encoding: "utf-8",
       )
     
     NoMethodError:
       undefined method `type' for nil
     # ./spec/v3/rfc_spec.rb:29:in `block (3 levels) in <top (required)>'

Finished in 0.30615 seconds (files took 0.14148 seconds to load)
5 examples, 4 failures
```

Actual error from `bundle console`:
```
irb(main):001> Rfcxml::V3::Rfc.from_xml(File.read('spec/xmlsource-rfc8650-latest/rfc8650.xml')).to_xml
gems/lutaml-model-0.3.5/lib/lutaml/model/xml_adapter/xml_document.rb:130:in `block in build_namespace_attributes': undefined method `type' for nil (NoMethodError)

                     attributes[mapping_rule.to].type
                                                ^^^^^
	from gems/lutaml-model-0.3.5/lib/lutaml/model/xml_adapter/xml_document.rb:120:in `each'
	from gems/lutaml-model-0.3.5/lib/lutaml/model/xml_adapter/xml_document.rb:120:in `build_namespace_attributes'
	from gems/lutaml-model-0.3.5/lib/lutaml/model/xml_adapter/xml_document.rb:134:in `block in build_namespace_attributes'
	from gems/lutaml-model-0.3.5/lib/lutaml/model/xml_adapter/xml_document.rb:120:in `each'
	from gems/lutaml-model-0.3.5/lib/lutaml/model/xml_adapter/xml_document.rb:120:in `build_namespace_attributes'
	from gems/lutaml-model-0.3.5/lib/lutaml/model/xml_adapter/xml_document.rb:134:in `block in build_namespace_attributes'
	from gems/lutaml-model-0.3.5/lib/lutaml/model/xml_adapter/xml_document.rb:120:in `each'
	from gems/lutaml-model-0.3.5/lib/lutaml/model/xml_adapter/xml_document.rb:120:in `build_namespace_attributes'
	from gems/lutaml-model-0.3.5/lib/lutaml/model/xml_adapter/xml_document.rb:134:in `block in build_namespace_attributes'
	from gems/lutaml-model-0.3.5/lib/lutaml/model/xml_adapter/xml_document.rb:120:in `each'
	from gems/lutaml-model-0.3.5/lib/lutaml/model/xml_adapter/xml_document.rb:120:in `build_namespace_attributes'
	from gems/lutaml-model-0.3.5/lib/lutaml/model/xml_adapter/xml_document.rb:134:in `block in build_namespace_attributes'
	from gems/lutaml-model-0.3.5/lib/lutaml/model/xml_adapter/xml_document.rb:120:in `each'
	from gems/lutaml-model-0.3.5/lib/lutaml/model/xml_adapter/xml_document.rb:120:in `build_namespace_attributes'
	from gems/lutaml-model-0.3.5/lib/lutaml/model/xml_adapter/xml_document.rb:134:in `block in build_namespace_attributes'
```

**Comment by ronaldtse** [comment]
@HassanAkbar there seems to be a Lutaml::Model issue here. Parsing works, but generating XML doesn't yet.
